blueprint/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user
from models import User
from helper import database as db


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    
    # code to show login page
    if request.method == "GET":
        return render_template('login.html')
    
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    
    # if the above check passes, then we know the user has the right credentials
    return redirect(url_for('main.home'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    
    # code to show signup page
    if request.method == "GET":
        return render_template('signup.html')
    
    # code to validate and add user to database goes here
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')
    agreed = True if request.form.get('agreed') else False
    
    if not agreed: # if user doesn't agree the terms, we want to redirect back to signup page so user can try again
        flash('You must agree to the privacy policy.')
        flash('You must agree to the terms & conditions')
        return redirect(url_for('auth.signup'))

    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

blueprint/main.py
from sched import scheduler
from flask import Blueprint, jsonify, render_template, request
from flask_login import login_required, current_user
from timetable import Schedule
from pathlib import Path
import csv, os

main = Blueprint('main', __name__)
schedule = Schedule()
base_dir = Path(__file__).parent.resolve()


def get_recommendations(day_name, lecture, subject):

    day_name = day_name.lower()
    Teachers = []
    if day_name == 'monday':
        with open(os.path.join(base_dir, 'dataset', 'monday.csv'), 'r') as read_obj:
            csv_reader = csv.reader(read_obj)
            list_of_csv = list(csv_reader)
            for row in list_of_csv:
                Teachers.append(row)
                print(row)
    elif day_name == 'tuesday':
        with open(os.path.join(base_dir, 'dataset', 'tuesday.csv'), 'r') as read_obj:
            csv_reader = csv.reader(read_obj)
            list_of_csv = list(csv_reader)
            for row in list_of_csv:
                Teachers.append(row)
                print(row)
    elif day_name == 'wednesday':
        with open(os.path.join(base_dir, 'dataset', 'wednesday.csv'), 'r') as read_obj:
            csv_reader = csv.reader(read_obj)
            list_of_csv = list(csv_reader)
            for row in list_of_csv:
                Teachers.append(row)
                print(row)
    elif day_name == 'thursday':
        with open(os.path.join(base_dir, 'dataset', 'thursday.csv'), 'r') as read_obj:
            csv_reader = csv.reader(read_obj)
            list_of_csv = list(csv_reader)
            for row in list_of_csv:
                Teachers.append(row)
                print(row)
    elif day_name == 'friday':
        with open(os.path.join(base_dir, 'dataset', 'friday.csv'), 'r') as read_obj:
            csv_reader = csv.reader(read_obj)
            list_of_csv = list(csv_reader)
            for row in list_of_csv:
                Teachers.append(row)
                print(row)
    
    possible_sub = {}
    no_class = []
    sub_possible_sub = []
    sub_no_class = []

    ab_lect = int(lecture)
    subject = subject.lower()


    # first priority (if subsequent lecture is free too)
    for i in Teachers:
        count = 0
        if i[ab_lect] != '1' and i[ab_lect-1] != '1' and i[ab_lect+1] != '1':             # looks for the possible substitutes
            possible_sub[i[0]] = i[-1]
            for j in i:                 # counts the total number of free periods
                if j == '0':
                    count += 1
            no_class.append(count)

    # second priority
    if possible_sub == {}:
        for i in Teachers:
            count = 0
            if i[ab_lect] == '0':
                possible_sub[i[0]] = i[-1]
                for j in i:
                    if j == '0':
                        count += 1
                no_class.append(count)

    print(possible_sub)  # prints the possible substitutes
    print(no_class)     # prints the total number of free periods

    result = []
    # to see if the teacher specializes in the same subject
    for i, (key, value) in enumerate(possible_sub.items()):
        count = 0
        if value == subject:
            sub_possible_sub.append(key)
            sub_no_class.append(no_class[i])
    if sub_possible_sub != []:
        suited_teacher = max(sub_no_class)  # gives the teacher with the most amount of free time
        print("The recommended teacher would be:")
        for i in range(len(sub_possible_sub)):
            if no_class[i] == suited_teacher:
                result.append(sub_possible_sub[i])  # prints the teacher to that index

    # if the possible candidates do not teach the preferred subject
    else:
        suited_teacher = max(no_class)  # gives the teacher with the most amount of free time
        print("The recommended teacher would be:")
        for i, (key, value) in enumerate(possible_sub.items()):
            if no_class[i] == suited_teacher:
                result.append(key)  # prints the teacher to that index

    return result, possible_sub

@main.route('/')
@login_required
def home():
    return render_template(
        'home.html',
        name=current_user.name,
        teachers=schedule.get_all_teachers()
    )


@main.route('/find-substitute-teachers', methods=['GET', 'POST'])
@login_required
def substitute():
    if request.method == "GET":
        return render_template(
            'substitute.html',
            name=current_user.name,
        )
    
    lecture = request.form.get('lecture')
    subject = request.form.get('subject')
    day = request.form.get('day')
    recommend,pos = get_recommendations(day,lecture,subject)
    return render_template(
        'result.html',
        results=recommend,
        poss=pos
    )


@main.route('/about/<teacher>')
@login_required
def about(teacher):
    return render_template('about.html', teacher=teacher)

templates/base.html
<!DOCTYPE html>
<html lang="en" class="bg-gray-50 {{ 'h-full' if h_full else '' }}">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Timetable | PIET</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
        integrity="sha512-wnea99uKIC3TJF7v4eKk4Y+lMz2Mklv18+r4na2Gn1abDRPPOeef95xTzdwGD9e6zXJBteMIhZ1+68QC5byJZw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body class="{{ 'h-full' if h_full else '' }}">

    <div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
        {% block content %}{% endblock %}

        {% if footer %}
        <footer class="flex-shrink-0 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 pt-16">
            <nav class="flex justify-center space-x-4">
                <a href="mailto:contact@piet.co.in"
                    class="text-sm font-medium text-gray-500 hover:text-gray-600">Contact
                    Support</a>
                <span class="inline-block border-l border-gray-300" aria-hidden="true"></span>
                <a href="javascript:void(0);" class="text-sm font-medium text-gray-500 hover:text-gray-600">Status</a>
                <span class="inline-block border-l border-gray-300" aria-hidden="true"></span>
                <a href="https://github.com/vishalxtyagi"
                    class="text-sm font-medium text-gray-500 hover:text-gray-600">Github</a>
            </nav>
        </footer>
        {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-xl font-semibold text-gray-900">{{ greetings }}, {{ name }}</h1>
            <p class="mt-2 text-sm text-gray-700">Welcome to teacher load management system for PIET</p>
        </div>

        <div class="mt-4 flex-shrink-0 flex md:mt-0 md:ml-4">
            <a href="{{ url_for('main.substitute') }}"
                class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Find substitute teachers
            </a>
            <a href="{{ url_for('auth.logout') }}"
                class="ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
                &nbsp;Logout
            </a>
        </div>
    </div>

    <div class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">

        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
            <ul role="list" class="divide-y divide-gray-200">
                {% for teacher in teachers %}
                <li>
                    <a href="{{ url_for('main.about', teacher=teacher) }}" class="block hover:bg-gray-50">
                        <div class="flex items-center px-4 py-4 sm:px-6">
                            <div class="min-w-0 flex-1 flex items-center">
                                <div class="flex-shrink-0">
                                    <img class="h-12 w-12 rounded-full"
                                        src="{{ url_for('static', filename='profile.jpg') }}" alt="">
                                </div>
                                <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
                                    <div>
                                        <p class="text-sm font-medium text-indigo-600 truncate">{{ teacher|title }}</p>
                                        <p class="mt-2 flex items-center text-sm text-gray-500">
                                            <!-- Heroicon name: solid/mail -->
                                            <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400"
                                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                                fill="currentColor" aria-hidden="true">
                                                <path
                                                    d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                                                <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                                            </svg>
                                            <span class="truncate">{{ teacher }}.ash@piet.co.in</span>
                                        </p>
                                    </div>
                                    <div class="hidden md:block">
                                        <div>
                                            <p class="text-sm text-gray-900">
                                                Total no. of leaves : 20
                                            </p>
                                            <p class="mt-2 flex items-center text-sm text-gray-500">
                                                <!-- Heroicon name: solid/check-circle -->
                                                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400"
                                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                                    fill="currentColor" aria-hidden="true">
                                                    <path fill-rule="evenodd"
                                                        d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                                        clip-rule="evenodd" />
                                                </svg>
                                                Present Today
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <!-- Heroicon name: solid/chevron-right -->
                                <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd"
                                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                        clip-rule="evenodd" />
                                </svg>
                            </div>
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% set h_full = True %}
{% set footer = True %}

{% block content %}
<div class="sm:mx-auto sm:w-full sm:max-w-md">
    <img class="mx-auto h-12 w-auto" src="{{ url_for('static', filename='piet-logo-dark.png') }}" alt="Workflow">
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Sign in to your account</h2>
    <p class="mt-2 text-center text-sm text-gray-600">
        Or
        <a href="mailto:contact@piet.co.in" class="font-medium text-indigo-600 hover:text-indigo-500"> having any issue,
            contact support.</a>
    </p>
</div>

<div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="rounded-md bg-red-50 p-4 mb-8">
        <div class="flex">
            <div class="flex-shrink-0">
                <!-- Heroicon name: solid/x-circle -->
                <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                    fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd"
                        d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                        clip-rule="evenodd" />
                </svg>
            </div>
            <div class="ml-3">
                <h3 class="text-sm font-medium text-red-800">There were {{ messages|length }} errors with your
                    submission</h3>
                <div class="mt-2 text-sm text-red-700">
                    <ul role="list" class="list-disc pl-5 space-y-1">
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <form class="space-y-6" action="#" method="POST">
            <div>
                <label for="email" class="block text-sm font-medium text-gray-700"> Email address </label>
                <div class="mt-1">
                    <input id="email" name="email" type="email" autocomplete="email" required
                        class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                </div>
            </div>

            <div>
                <label for="password" class="block text-sm font-medium text-gray-700"> Password </label>
                <div class="mt-1">
                    <input id="password" name="password" type="password" autocomplete="current-password" required
                        class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                </div>
            </div>

            <div class="flex items-center justify-between">
                <div class="flex items-center">
                    <input id="remember-me" name="remember-me" type="checkbox"
                        class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded">
                    <label for="remember-me" class="ml-2 block text-sm text-gray-900"> Remember me </label>
                </div>

                <div class="text-sm">
                    <a href="javascript:void(0);" class="font-medium text-indigo-600 hover:text-indigo-500">
                        Forgot
                        your password?
                    </a>
                </div>
            </div>

            <div>
                <button type="submit"
                    class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Sign
                    in</button>
            </div>
        </form>

        <div class="mt-6">
            <div class="relative">
                <div class="absolute inset-0 flex items-center">
                    <div class="w-full border-t border-gray-300"></div>
                </div>
                <div class="relative flex justify-center text-sm">
                    <span class="px-2 bg-white text-gray-500"> Or continue with </span>
                </div>
            </div>

            <div class="mt-6">

                <div>
                    <a href="{{ url_for('auth.signup') }}"
                        class="w-full inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                        <span>Request for new account</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/result.html
{% extends 'base.html' %}

{% block content %}
<div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-xl font-semibold text-gray-900">{{ greetings }}, {{ name }}</h1>
            <p class="mt-2 text-sm text-gray-700">Welcome to teacher load management system for PIET</p>
        </div>

        <div class="mt-4 flex-shrink-0 flex md:mt-0 md:ml-4">
            <a href="{{ url_for('main.substitute') }}"
                class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Find substitute teachers
            </a>
            <a href="{{ url_for('auth.logout') }}"
                class="ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
                &nbsp;Logout
            </a>
        </div>
    </div>

    <div class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">

        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
            <h2>Recommended</h2>
            <ul role="list" class="divide-y divide-gray-200">
                {% for i in results %}
                <li>
                    <div class="block hover:bg-gray-50">
                        <div class="flex items-center px-4 py-4 sm:px-6">
                            <div class="min-w-0 flex-1 flex items-center">
                                <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
                                    <div>
                                        <p class="text-sm font-medium text-indigo-600 truncate">{{ i }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <h2>Possible Substitutes</h2>
            <ul role="list" class="divide-y divide-gray-200">
                {% for i in poss %}
                <li>
                    <div class="block hover:bg-gray-50">
                        <div class="flex items-center px-4 py-4 sm:px-6">
                            <div class="min-w-0 flex-1 flex items-center">
                                <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
                                    <div>
                                        <p class="text-sm font-medium text-indigo-600 truncate">{{ i }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/substitute.html
{% extends 'base.html' %}

{% set h_full = True %}

{% block content %}
<div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-xl font-semibold text-gray-900">{{ greetings }}, {{ name }}</h1>
            <p class="mt-2 text-sm text-gray-700">Welcome to teacher load management system for PIET</p>
        </div>
        <div class="mt-4 flex-shrink-0 flex md:mt-0 md:ml-4"><a href="{{ url_for('main.home') }}"
                class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Go Back
            </a>
            <a href="{{ url_for('auth.logout') }}"
                class="ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
                &nbsp;Logout
            </a>
        </div>
    </div>

    <div class="-mx-4 mt-8 overflow-hidden sm:-mx-6 md:mx-0 md:rounded-lg">
        <form action="#" method="POST">
            <div class="shadow sm:rounded-md sm:overflow-hidden">
                <div class="bg-white py-6 px-4 space-y-6 sm:p-6">
                    <div>
                        <h3 class="text-lg leading-6 font-medium text-gray-900">Substitute Teacher</h3>
                        <p class="mt-1 text-sm text-gray-500">Please select the critera to find the best fitted
                            substitute teacher</p>
                    </div>
                    <div class="isolate -space-y-px rounded-md shadow-sm">
                        <div class="relative border border-gray-300 rounded-md rounded-b-none px-3 py-2 focus-within:z-10 focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
                          <label for="lecture" class="block text-xs font-medium text-gray-900">lecture</label>
                          <input type="text" name="lecture" id="lecture" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="e.g., 1,2,3">
                        </div>
                        <div class="relative border border-gray-300 rounded-md rounded-b-none px-3 py-2 focus-within:z-10 focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
                            <label for="day" class="block text-xs font-medium text-gray-900">day</label>
                            <input type="text" name="day" id="day" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="e.g., Monday, Tuesday">
                          </div>
                          <div class="relative border border-gray-300 rounded-md rounded-b-none px-3 py-2 focus-within:z-10 focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
                            <label for="subject" class="block text-xs font-medium text-gray-900">subject</label>
                            <input type="text" name="subject" id="subject" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="e.g., Math">
                          </div>
                      </div>
                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                        <button type="submit"
                            class="bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600">Save</button>
                    </div>
                </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}